# Generated by Django 5.1.7 on 2025-09-29 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_merge_20250623_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedproject',
            name='cdb_id',
            field=models.ForeignKey(blank=True, default=None, help_text='The ConceptDB to be set for this exported project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.conceptdb'),
        ),
        migrations.AddField(
            model_name='exportedproject',
            name='modelpack_id',
            field=models.ForeignKey(blank=True, default=None, help_text='The ModelPack to be set for this exported project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.modelpack'),
        ),
        migrations.AddField(
            model_name='exportedproject',
            name='vocab_id',
            field=models.ForeignKey(blank=True, default=None, help_text='The Vocabulary to be set for this exported project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vocabulary'),
        ),
    ]
