# Generated by Django 5.1.7 on 2025-10-07 00:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0091_exportedproject_cdb_id_exportedproject_modelpack_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportedproject',
            name='cdb_search_filter_id',
            field=models.ForeignKey(blank=True, default=None, help_text='The CDB that will be used for concept lookup. This specific CDB should have been "imported" via the CDB admin screen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concept_source_exported_project', to='api.conceptdb'),
        ),
        migrations.AddField(
            model_name='exportedproject',
            name='import_project_name_suffix',
            field=models.CharField(default=' IMPORTED', help_text='The suffix to be added to the project name', max_length=100),
        ),
        migrations.AddField(
            model_name='exportedproject',
            name='members',
            field=models.ManyToManyField(blank=True, default=None, help_text='The annotators for the project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exportedproject',
            name='set_validated_docs',
            field=models.BooleanField(default=False, help_text='Whether to set the validated documents, e.g. their annotation submit status.'),
        ),
        migrations.AlterField(
            model_name='conceptdb',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z][a-zA-Z0-9_]*$', 'a-zA-Z for first character required. Alpahanumeric or _ thereafter are allowed for CDB names')]),
        ),
    ]
